version: 2

publications:
  - url: https://oss.sonatype.org/content/groups/public/com/launchdarkly/launchdarkly-logging/
    description: Sonatype
  - url: https://javadoc.io/doc/com.launchdarkly/launchdarkly-logging
    description: documentation (javadoc.io)

template:
  - docker:
      image: gradle:7.3.3-jdk8
    template:
      name: gradle

documentation:
  gitHubPages: true
